"""Freeze source Unicode/ftfy tables; development only, never run by CMake.

Generated tables preserve the installed upstream tokenizer's Unicode versions
instead of silently inheriting the regex engine's different character classes.
"""
import html
import json
import re
import unicodedata
from pathlib import Path
import ftfy
import regex
from ftfy import chardata, fixes, badness


def literal(s):
    data = s.encode('utf-8')
    # MSVC limits individual string literals, including their escape spelling.
    # Adjacent literals retain one array and one trailing NUL without runtime work.
    chunks = [data[i:i + 512] for i in range(0, len(data), 512)] or [b'']
    return '\n'.join('"' + ''.join(
        chr(x) if 32 <= x < 127 and x not in (34, 92) else '\\%03o' % x
        for x in chunk) + '"' for chunk in chunks)


def ranges(predicate):
    pieces = []
    first = previous = None
    for cp in range(0x110000):
        if predicate(chr(cp)):
            if first is None: first = cp
            previous = cp
        elif first is not None:
            pieces.append((first, previous)); first = None
    if first is not None: pieces.append((first, previous))
    return ''.join('\\x{%x}' % x + ('-\\x{%x}' % y if x != y else '') for x, y in pieces)


def compact(pattern):
    out = []; in_class = False; i = 0
    while i < len(pattern):
        c = pattern[i]
        if c == '\\': out.append(pattern[i:i+2]); i += 2; continue
        if c == '[': in_class = True
        if c == ']': in_class = False
        if not in_class and c == '#':
            i = pattern.find('\n', i)
            if i == -1: break
            continue
        if c == '.' and not in_class: out.append('[^\\n]')
        elif in_class or not c.isspace(): out.append(c)
        i += 1
    return ''.join(out)


def main():
    assert ftfy.__version__ == '6.1.1' and unicodedata.unidata_version == '15.0.0'
    assert regex.__version__ == '2025.11.3'
    out = ['// Generated by native/tools/generate_tokenizer_tables.py; do not edit.',
           '// ftfy 6.1.1; CPython Unicode 15.0.0; regex 2025.11.3.',
           '// Tables adapted from ftfy (MIT), CPython (PSF), and Unicode properties.',
           '#pragma once', '#include <cstdint>', 'namespace sam3::tokenizer_data {',
           'struct Mapping { uint32_t code; const char* value; };',
           'struct Entity { const char* name; const char* value; };']
    py_space = ranges(str.isspace); py_word = ranges(lambda s: s.isalnum() or s == '_')
    py_digit = ranges(str.isdecimal)
    properties = {name: ranges(regex.compile(expr,regex.I if name!='spaces' else 0).fullmatch) for name, expr in
                  [('letters', r'\p{L}'), ('numbers', r'\p{N}'), ('spaces', r'\s'),
                   ('other', r'[^\s\p{L}\p{N}]')]}
    for name, chars in properties.items(): out.append(f'inline constexpr char {name}[] = {literal(chars)};')
    out.append(f'inline constexpr char py_spaces[] = {literal(py_space)};')
    for name, obj in [('badness',badness.BADNESS_RE), ('utf8_detector',chardata.UTF8_DETECTOR_RE),
                      ('altered',chardata.ALTERED_UTF8_RE), ('lossy',chardata.LOSSY_UTF8_RE),
                      ('a_grave',fixes.A_GRAVE_WORD_RE), ('ansi',fixes.ANSI_RE),
                      ('html_strict',chardata.HTML_ENTITY_RE), ('html_loose',html._charref)]:
        pattern = obj.pattern.decode('latin1') if isinstance(obj.pattern,bytes) else obj.pattern
        if obj.flags & re.VERBOSE: pattern = compact(pattern)
        pattern = pattern.replace(r'\s','['+py_space+']').replace(r'\w','['+py_word+']').replace(r'\d','['+py_digit+']')
        out.append(f'inline constexpr char {name}[] = {literal(pattern)};')
    for name, mapping in [('html5',html.entities.html5), ('ftfy_entities',chardata.HTML_ENTITIES)]:
        out.append(f'inline constexpr Entity {name}[] = {{')
        out.extend('{'+literal(k)+','+literal(v)+'},' for k,v in sorted(mapping.items()))
        out.append('};')
    candidates = set(chardata.CONTROL_CHARS) | set(chardata.LIGATURES) | set(chardata.WIDTH_MAP) | set(range(160)) | {0x2bc,0x2028,0x2029} | set(range(0x2018,0x2020))
    mapping = {}
    for cp in sorted(candidates):
        s = chr(cp)
        for fn in [fixes.fix_c1_controls,fixes.fix_latin_ligatures,fixes.fix_character_width,fixes.uncurl_quotes,fixes.fix_line_breaks]: s = fn(s)
        if s != chr(cp): mapping[cp] = s
    for name, values in [('simple_fixes',mapping), ('invalid_charrefs',html._invalid_charrefs)]:
        out.append(f'inline constexpr Mapping {name}[] = {{')
        out.extend('{'+str(k)+','+literal(v)+'},' for k,v in sorted(values.items()))
        out.append('};')
    out.append('inline constexpr uint32_t invalid_codepoints[] = {'+','.join(map(str,sorted(html._invalid_codepoints)))+'};')
    out.append('inline constexpr uint32_t controls[] = {'+','.join(map(str,sorted(chardata.CONTROL_CHARS)))+'};')
    out.append('inline constexpr uint32_t codecs[][256] = {')
    for codec in chardata.CHARMAP_ENCODINGS:
        out.append('{'+','.join(str(ord(bytes([i]).decode(codec))) for i in range(256))+'},')
    out.extend(['};', '}'])
    path = Path('native/src/tokenizer_tables.h'); path.write_text('\n'.join(out)+'\n')
    print(json.dumps(dict(path=str(path),bytes=path.stat().st_size,ftfy=ftfy.__version__,unicode=unicodedata.unidata_version,regex=regex.__version__)))


if __name__ == '__main__': main()
