/* Compare file-owned predictors to existing RGB callback predictors. */
#include "sam3/c_api.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#define CHECK(x) do{if(!(x)){fprintf(stderr,"line %d: %s (%s)\n",__LINE__,#x,sam3_last_error());exit(1);}}while(0)
#define OK(x) CHECK((x)==SAM3_OK)
static int checks=0;
static void equal(sam3_result* a,sam3_result* b){int64_t an,bn;OK(sam3_result_field_count(a,&an));OK(sam3_result_field_count(b,&bn));CHECK(an==bn);for(int64_t i=0;i<an;++i){const char *ak,*bk;sam3_tensor_view av,bv;OK(sam3_result_field_name(a,i,&ak));OK(sam3_result_field_name(b,i,&bk));CHECK(strcmp(ak,bk)==0);OK(sam3_result_get(a,ak,&av));OK(sam3_result_get(b,bk,&bv));CHECK(av.dtype==bv.dtype && av.rank==bv.rank && av.bytes==bv.bytes);for(int j=0;j<av.rank;++j)CHECK(av.shape[j]==bv.shape[j]);CHECK(!av.bytes || memcmp(av.data,bv.data,(size_t)av.bytes)==0);}++checks;}
struct Provider {sam3_media* media;uint8_t* pixels;};
static int32_t read_rgb(void* opaque,int64_t index,sam3_rgb_view* view){struct Provider* p=(struct Provider*)opaque;sam3_result* r=NULL;if(sam3_media_read_frame(p->media,index,&r)!=SAM3_OK)return -1;sam3_tensor_view rgb;OK(sam3_result_get(r,"rgb",&rgb));int64_t h=rgb.shape[1],w=rgb.shape[2];free(p->pixels);p->pixels=(uint8_t*)malloc((size_t)(h*w*3));CHECK(p->pixels);const uint8_t* src=(const uint8_t*)rgb.data;for(int64_t i=0;i<h*w;++i)for(int c=0;c<3;++c)p->pixels[3*i+c]=src[c*h*w+i];*view=(sam3_rgb_view){p->pixels,(uint64_t)(h*w*3),h,w,w*3};sam3_result_release(r);return 0;}
struct Outputs {sam3_result** values;size_t size,used;int compare;};
static int32_t output(void* opaque,const sam3_result* result){struct Outputs* o=(struct Outputs*)opaque;if(o->compare){CHECK(o->used<o->size);equal(o->values[o->used++],(sam3_result*)result);}else{o->values=(sam3_result**)realloc(o->values,(o->size+1)*sizeof(*o->values));CHECK(o->values);OK(sam3_result_retain(result,&o->values[o->size++]));}return 0;}
int main(int argc,char** argv){CHECK(argc==7);const int model=atoi(argv[2]),image=strcmp(argv[3],"image")==0;OK(sam3_runtime_configure(4,0));sam3_media_options mo;OK(sam3_media_options_init(&mo));mo.image_only=image;sam3_media* media=NULL;OK(sam3_media_open(argv[4],&mo,&media));sam3_result* info=NULL;OK(sam3_media_info(media,&info));sam3_tensor_view n,h,w;OK(sam3_result_get(info,"frames",&n));OK(sam3_result_get(info,"height",&h));OK(sam3_result_get(info,"width",&w));sam3_predictor_options options;OK(sam3_predictor_options_init(&options,model));options.image_only=image;options.centers=1;options.tracking.frames=*(int64_t*)n.data;options.tracking.height=*(int64_t*)h.data;options.tracking.width=*(int64_t*)w.data;sam3_result_release(info);
  sam3_context_options co;OK(sam3_context_options_init(&co));co.weight_directory=argv[1];co.model=model;co.device="cuda";co.precision=SAM3_BF16_REFERENCE;co.vocabulary_path=argv[5];sam3_context* context=NULL;OK(sam3_context_create(&co,&context));sam3_predictor *file=NULL,*raw=NULL;OK(sam3_predictor_create_from_media(context,media,&options,&file));sam3_media_release(media); /* file predictor owns its source */
  struct Provider provider={0};OK(sam3_media_open(argv[4],&mo,&provider.media));options.tracking.provider=read_rgb;options.tracking.provider_user=&provider;OK(sam3_predictor_create(context,&options,&raw));sam3_context_release(context);
  sam3_utf8_view text={argv[6],strlen(argv[6])};sam3_semantic_prompt prompt;OK(sam3_semantic_prompt_init(&prompt));prompt.text=&text;sam3_result *a=NULL,*b=NULL;OK(sam3_predictor_add_prompt(raw,0,&prompt,&a));OK(sam3_predictor_add_prompt(file,0,&prompt,&b));equal(a,b);sam3_result_release(a);sam3_result_release(b);
  if(!image){struct Outputs outputs={0};OK(sam3_predictor_propagate(raw,0,-1,0,0,output,&outputs));outputs.compare=1;OK(sam3_predictor_propagate(file,0,-1,0,0,output,&outputs));CHECK(outputs.used==outputs.size && outputs.size==(size_t)options.tracking.frames);for(size_t i=0;i<outputs.size;++i)sam3_result_release(outputs.values[i]);free(outputs.values);}
  OK(sam3_predictor_reset(raw));OK(sam3_predictor_reset(file));OK(sam3_predictor_add_prompt(raw,0,&prompt,&a));OK(sam3_predictor_add_prompt(file,0,&prompt,&b));equal(a,b);sam3_predictor_release(file);sam3_predictor_release(raw);sam3_media_release(provider.media);free(provider.pixels);equal(a,b);sam3_result_release(a);sam3_result_release(b);printf("model=%d image=%d exact_result_sets=%d source_and_context_lifetime=passed\n",model,image,checks);return 0;
}
