#include "sam3/video_interaction.h"
#include "sam3/video_edit.h"
#include <ATen/Parallel.h>
#include <iostream>
int main(){try{
 at::set_num_threads(1);sam3::VideoInteractionState state(sam3::AssociationPolicy::Sam3,10,3,5);
 TORCH_CHECK(state.route().type==sam3::VideoActionType::Full,"initial route");state.append({sam3::VideoActionType::Refine,3,std::vector<int64_t>{7,2,7}});TORCH_CHECK(state.route().ids==std::optional<std::vector<int64_t>>({2,7}),"partial IDs");TORCH_CHECK(sam3::video_object_was_refined(state.actions(),7),"refined history");state.append({sam3::VideoActionType::Partial,0,std::vector<int64_t>{7,2}});TORCH_CHECK(state.route().type==sam3::VideoActionType::Fetch,"boundary fetch");TORCH_CHECK(state.route({7},true).type==sam3::VideoActionType::Partial && state.route({},true).type==sam3::VideoActionType::Full,"forced propagation");
 sam3::VideoOutput out;out.cached_masks[7]=at::ones({1,3,5},at::kBool);state.record(3,out);out.cached_masks[7].zero_();sam3::VideoMetadata metadata;metadata.object_scores[7]=1.;TORCH_CHECK(state.fetch(3,metadata).masks.all().item<bool>(),"cache not isolated");state.forget_object(7);TORCH_CHECK(state.fetch(3,metadata).ids.numel()==0,"removed cached ID");state.reset();TORCH_CHECK(state.actions().empty() && state.cached_frames().empty(),"reset");const auto range=sam3::video_processing_range(10,{3},{},{},true);TORCH_CHECK(range.first==2 && range.end==0 && range.step==-1,"reverse excludes start");
 sam3::VideoOutput original;original.cached_masks[7]=at::ones({1,3,5},at::kBool);state.record(3,original);
 auto invalid=original;invalid.cached_masks[8]=at::Tensor();bool failed=false;try{state.record(3,invalid);}catch(const c10::Error&){failed=true;}
 TORCH_CHECK(failed && state.cached_frames().at(3).size()==1 && state.cached_frames().at(3).at(7).all().item<bool>(),"failed replacement lost the preceding frame");
 failed=false;try{state.record(4,invalid);}catch(const c10::Error&){failed=true;}TORCH_CHECK(failed && !state.cached_frames().count(4),"failed initial record left a partial frame");
 sam3::VideoInteractionState mux(sam3::AssociationPolicy::Sam31,10,3,5);mux.append({sam3::VideoActionType::Cancel,{},{}});TORCH_CHECK(mux.route().type==sam3::VideoActionType::Full,"cancel-only route");bool rejected=false;try{mux.fetch(0,metadata);}catch(const c10::Error&){rejected=true;}TORCH_CHECK(rejected,"SAM31 missing cache fetch");sam3::Sam31VideoSessions sessions;auto empty_metadata=sam3::initialize_video_metadata(1);sam3::VideoOutput stale;stale.cached_masks[99]=at::ones({1,3,5},at::kBool);mux.record(2,stale);sam3::remove_video_user_object(99,sessions,empty_metadata,mux);sam3::remove_video_user_object(99,sessions,empty_metadata,mux);TORCH_CHECK(mux.cached_frames().at(2).empty() && mux.actions().size()==3 && empty_metadata.object_ids().empty() && empty_metadata.buckets_per_rank[0]==0,"repeated unknown removal must forget cache and log both actions");std::cout<<"interaction routing/cache/reset passed\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
