cmake_minimum_required(VERSION 3.21)
# Run explicitly after installation. SDK and LibTorch inputs must be trusted.
if(NOT IS_DIRECTORY "${SAM3_SDK_ROOT}" OR NOT IS_DIRECTORY "${SAM3_TORCH_ROOT}/lib")
  message(FATAL_ERROR "Set SAM3_SDK_ROOT to an installed SDK and SAM3_TORCH_ROOT to its matching standalone LibTorch")
endif()
file(REAL_PATH "${SAM3_SDK_ROOT}" sdk)
file(REAL_PATH "${SAM3_TORCH_ROOT}" torch)
if(torch MATCHES "(site|dist)-packages")
  message(FATAL_ERROR "Use a standalone LibTorch distribution, not a Python wheel")
endif()
if(WIN32)
  set(runtime "${sdk}/bin")
  set(library "${runtime}/sam3_native.dll")
  set(ENV{PATH} "${torch}/lib;$ENV{PATH}")
  set(system_excludes ".*[/\\][Ss]ystem32[/\\].*" ".*[/\\][Ss]ys[Ww][Oo][Ww]64[/\\].*")
  set(pre_excludes "api-ms-.*" "ext-ms-.*")
  file(GLOB plugins "${torch}/lib/cudnn*.dll" "${torch}/lib/nvrtc*.dll" "${torch}/lib/torch_cuda_linalg.dll" "${torch}/lib/caffe2_nvrtc.dll")
elseif(UNIX AND NOT APPLE)
  set(runtime "${sdk}/lib")
  if(DEFINED SAM3_LIBDIR)
    set(runtime "${sdk}/${SAM3_LIBDIR}")
  endif()
  set(library "${runtime}/libsam3_native.so")
  set(ENV{LD_LIBRARY_PATH} "${torch}/lib")
  # The OS loader, C/C++ runtimes and NVIDIA driver remain host prerequisites.
  set(pre_excludes "^lib(c|m|dl|pthread|rt|util|resolv|gcc_s|stdc\\+\\+)\\.so.*" "^ld-linux.*" "^libcuda\\.so.*" "^libnvidia-.*")
  set(system_excludes "")
  file(GLOB plugins "${torch}/lib/libcudnn*.so*" "${torch}/lib/libnvrtc*.so*" "${torch}/lib/libtorch_cuda_linalg.so*" "${torch}/lib/libcaffe2_nvrtc.so*")
else()
  message(FATAL_ERROR "Runtime bundling currently supports Windows and Linux")
endif()
if(NOT EXISTS "${library}")
  message(FATAL_ERROR "Installed native library not found: ${library}")
endif()
# Stage the selected FFmpeg distribution before resolving dependencies so an
# identically named system build cannot silently replace it in the SDK.
if(DEFINED SAM3_MEDIA_ROOT)
  file(REAL_PATH "${SAM3_MEDIA_ROOT}" media)
  set(media_libraries "")
  foreach(component avformat avcodec avutil swscale swresample)
    if(WIN32)
      file(GLOB media_component "${media}/bin/${component}*.dll" "${media}/lib/${component}*.dll")
    else()
      file(GLOB media_component "${media}/lib/lib${component}.so*")
    endif()
    if(NOT media_component)
      message(FATAL_ERROR "Missing ${component} runtime in SAM3_MEDIA_ROOT")
    endif()
    list(APPEND media_libraries ${media_component})
  endforeach()
  file(INSTALL ${media_libraries} DESTINATION "${runtime}" TYPE SHARED_LIBRARY FOLLOW_SYMLINK_CHAIN)
endif()
file(GET_RUNTIME_DEPENDENCIES LIBRARIES "${library}" ${plugins}
  DIRECTORIES "${torch}/lib" ${SAM3_RUNTIME_SEARCH_DIRS}
  PRE_EXCLUDE_REGEXES ${pre_excludes}
  POST_EXCLUDE_REGEXES ${system_excludes}
  RESOLVED_DEPENDENCIES_VAR dependencies UNRESOLVED_DEPENDENCIES_VAR missing
  CONFLICTING_DEPENDENCIES_PREFIX conflict)
if(missing)
  message(FATAL_ERROR "Unresolved runtime dependencies: ${missing}")
endif()
# A relocated existing SDK and plugin input directories can contain identical
# copies of one SONAME. Accept only byte-identical candidates; genuine version
# conflicts still fail instead of depending on platform search order.
foreach(name IN LISTS conflict_FILENAMES)
  set(candidates "${conflict_${name}}")
  list(GET candidates 0 selected)
  file(SHA256 "${selected}" expected_digest)
  foreach(candidate IN LISTS candidates)
    file(SHA256 "${candidate}" candidate_digest)
    if(NOT candidate_digest STREQUAL expected_digest)
      message(FATAL_ERROR "Conflicting runtime versions for ${name}: ${candidates}")
    endif()
    cmake_path(IS_PREFIX runtime "${candidate}" NORMALIZE from_sdk)
    if(from_sdk)
      set(selected "${candidate}")
    endif()
  endforeach()
  list(APPEND dependencies "${selected}")
endforeach()
set(files ${dependencies} ${plugins} ${media_libraries})
list(REMOVE_DUPLICATES files)
set(manifest "Standalone LibTorch: ${torch}\nRuntime files (SHA256 then installed filename):\n")
foreach(path IN LISTS files)
  get_filename_component(name "${path}" NAME)
  if(name MATCHES "torch_python|libpython|python[0-9]|libmpi|libuc[pxs]|torch_nvshmem")
    message(FATAL_ERROR "Unexpected development/Python runtime dependency: ${path}")
  endif()
  if(name MATCHES "^(lib)?(torch|c10)")
    cmake_path(IS_PREFIX torch "${path}" NORMALIZE from_torch)
    if(NOT from_torch)
      cmake_path(IS_PREFIX runtime "${path}" NORMALIZE already_bundled)
      if(NOT already_bundled OR NOT EXISTS "${torch}/lib/${name}")
        message(FATAL_ERROR "LibTorch dependency resolved outside the supplied distribution: ${path}")
      endif()
      file(SHA256 "${path}" installed_digest)
      file(SHA256 "${torch}/lib/${name}" source_digest)
      if(NOT installed_digest STREQUAL source_digest)
        message(FATAL_ERROR "Installed LibTorch differs from the supplied distribution: ${path}; use a clean SDK install")
      endif()
    endif()
  endif()
  file(INSTALL "${path}" DESTINATION "${runtime}" TYPE SHARED_LIBRARY FOLLOW_SYMLINK_CHAIN)
  file(SHA256 "${runtime}/${name}" digest)
  string(APPEND manifest "${digest}  ${name}\n")
endforeach()
file(WRITE "${sdk}/share/sam3-native/runtime-files.txt" "${manifest}")
if(DEFINED SAM3_RUNTIME_NOTICES)
  file(INSTALL "${SAM3_RUNTIME_NOTICES}/" DESTINATION "${sdk}/share/sam3-native/notices" TYPE DIRECTORY)
endif()
message(STATUS "Bundled runtime in ${runtime}; keep its upstream license/notice files with distribution")
