# Shared declaration for native tests and command-line probes.
function(sam3_add_native_tool target)
  add_executable(${target} ${ARGN})
  target_link_libraries(${target} PRIVATE sam3_native)
endfunction()

sam3_add_native_tool(sam3_vision_experiments_test tests/vision_experiments_test.cpp)
add_test(NAME vision_experiments_cpu COMMAND sam3_vision_experiments_test valid)
add_test(NAME vision_experiments_invalid_scope_cpu COMMAND sam3_vision_experiments_test invalid_scope)
add_test(NAME vision_experiments_invalid_int4_cpu COMMAND sam3_vision_experiments_test invalid_int4)
add_test(NAME vision_experiments_invalid_part_cpu COMMAND sam3_vision_experiments_test invalid_part)
add_test(NAME vision_experiments_invalid_projection_scope_cpu COMMAND sam3_vision_experiments_test invalid_projection_scope)

sam3_add_native_tool(sam3_vision_position_test tests/vision_position_test.cpp)
add_test(NAME vision_position COMMAND sam3_vision_position_test cpu)
sam3_add_native_tool(sam3_native_media_test tests/media_test.cpp)
add_test(NAME media COMMAND sam3_native_media_test)
add_executable(sam3_media_predictor_c_probe tools/media_predictor_c_probe.c)
target_compile_features(sam3_media_predictor_c_probe PRIVATE c_std_11)
target_link_libraries(sam3_media_predictor_c_probe PRIVATE sam3_native)
add_executable(sam3_media_c_probe tools/media_c_probe.c)
target_compile_features(sam3_media_c_probe PRIVATE c_std_11)
target_link_libraries(sam3_media_c_probe PRIVATE sam3_native)
add_executable(sam3_native_smoke smoke/main.cpp)
target_compile_features(sam3_native_smoke PRIVATE cxx_std_17)
target_link_libraries(sam3_native_smoke PRIVATE ${TORCH_LIBRARIES})
sam3_add_native_tool(sam3_native_ops_test tests/ops_test.cpp)
sam3_add_native_tool(sam3_rotary_pair_test tests/rotary_pair_test.cpp)
add_test(NAME rotary_pair COMMAND sam3_rotary_pair_test cpu)
sam3_add_native_tool(sam3_vision_fusion_test tests/vision_fusion_test.cpp)
add_test(NAME vision_fusion COMMAND sam3_vision_fusion_test)
sam3_add_native_tool(sam3_rotary_test tests/rotary_test.cpp)
sam3_add_native_tool(sam3_video_mask_cache_test tests/video_mask_cache_test.cpp)
sam3_add_native_tool(sam3_video_mask_cache_benchmark tools/video_mask_cache_benchmark.cpp)
sam3_add_native_tool(sam3_video_cache_fetch_probe tools/video_cache_fetch_probe.cpp)
sam3_add_native_tool(sam3_semantic_text_probe tools/semantic_text_probe.cpp)
if(SAM3_WITH_CUDA)
  add_executable(sam3_vision_position_stream_test tests/vision_position_test.cpp)
  target_compile_definitions(sam3_vision_position_stream_test PRIVATE SAM3_TEST_CUDA_STREAM)
  target_link_libraries(sam3_vision_position_stream_test PRIVATE sam3_native)
  target_compile_definitions(sam3_semantic_text_probe PRIVATE SAM3_BENCH_CUDA)
  sam3_add_native_tool(sam3_vision_fusion_benchmark tools/vision_fusion_benchmark.cpp)
  sam3_add_native_tool(sam3_compute_storage_probe tools/compute_storage_probe.cpp)
  target_compile_definitions(sam3_video_cache_fetch_probe PRIVATE SAM3_BENCH_CUDA)
  target_compile_definitions(sam3_video_mask_cache_benchmark PRIVATE SAM3_BENCH_CUDA)
  add_executable(sam3_vision_fusion_stream_test tests/vision_fusion_test.cpp)
  target_compile_definitions(sam3_vision_fusion_stream_test PRIVATE SAM3_TEST_CUDA_STREAM)
  target_link_libraries(sam3_vision_fusion_stream_test PRIVATE sam3_native)
  add_executable(sam3_rotary_pair_stream_test tests/rotary_pair_test.cpp)
  target_compile_definitions(sam3_rotary_pair_stream_test PRIVATE SAM3_TEST_CUDA_STREAM)
  target_link_libraries(sam3_rotary_pair_stream_test PRIVATE sam3_native)
  add_executable(sam3_rotary_stream_test tests/rotary_test.cpp)
  target_compile_definitions(sam3_rotary_stream_test PRIVATE SAM3_TEST_CUDA_STREAM)
  target_link_libraries(sam3_rotary_stream_test PRIVATE sam3_native)
endif()
sam3_add_native_tool(sam3_native_weights_test tests/weights_test.cpp)
sam3_add_native_tool(sam3_weights_large_test tests/weights_large_test.cpp)
sam3_add_native_tool(sam3_inference_settings_test tests/inference_settings_test.cpp)
sam3_add_native_tool(sam3_native_multiplex_test tests/multiplex_test.cpp)
sam3_add_native_tool(sam3_weights tools/weights_cli.cpp)
sam3_add_native_tool(sam3_text tools/text_cli.cpp)
sam3_add_native_tool(sam3_tokenize tools/tokenizer_cli.cpp)
sam3_add_native_tool(sam3_tokenizer_test tests/tokenizer_test.cpp)
add_executable(sam3_image_benchmark tools/image_benchmark.cpp)
if(SAM3_WITH_CUDA)
  sam3_add_native_tool(sam3_image_latency tools/image_latency.cpp)
  add_executable(sam3_gemm_algorithms tools/gemm_algorithms.cpp)
  target_link_libraries(sam3_gemm_algorithms PRIVATE sam3_native CUDA::cublasLt)
  add_executable(sam3_int8_lt_bench tools/int8_lt_bench.cpp)
  target_link_libraries(sam3_int8_lt_bench PRIVATE sam3_native CUDA::cublasLt)
  add_executable(sam3_approx_bench tools/approx_bench.cpp tools/approx_kernels.cu)
  sam3_add_native_tool(sam3_pixel_bench tools/pixel_bench.cpp)
  target_link_libraries(sam3_approx_bench PRIVATE sam3_native)
  sam3_add_native_tool(sam3_boundary_bench tools/boundary_bench.cpp tools/approx_kernels.cu tools/approx_boundary.cu)
  sam3_add_native_tool(sam3_qkv_rope_bench tools/qkv_rope_bench.cpp tools/approx_kernels.cu)
  sam3_add_native_tool(sam3_fc2_norm_bench tools/fc2_norm_bench.cpp tools/approx_kernels.cu src/vision_fusion_cuda.cu)
endif()
target_link_libraries(sam3_image_benchmark PRIVATE sam3_native)
if(SAM3_WITH_CUDA)
  target_compile_definitions(sam3_image_benchmark PRIVATE SAM3_BENCH_CUDA)
endif()
sam3_add_native_tool(sam3_image_results_test tests/image_results_test.cpp)
if(SAM3_WITH_CUDA)
  target_compile_definitions(sam3_image_results_test PRIVATE SAM3_TEST_CUDA_STATS)
endif()
sam3_add_native_tool(sam3_image_probe tools/image_probe.cpp)
sam3_add_native_tool(sam3_interactive tools/interactive_cli.cpp)
sam3_add_native_tool(sam3_interactive_image tools/interactive_image_cli.cpp)
sam3_add_native_tool(sam3_video_heads tools/video_heads_cli.cpp)
sam3_add_native_tool(sam3_memory tools/memory_cli.cpp)
sam3_add_native_tool(sam3_memory_attention tools/memory_attention_cli.cpp)
sam3_add_native_tool(sam3_temporal tools/temporal_cli.cpp)
sam3_add_native_tool(sam3_multiplex_propagation tools/multiplex_propagation_cli.cpp)
sam3_add_native_tool(sam3_multiplex_temporal tools/multiplex_temporal_cli.cpp)
sam3_add_native_tool(sam3_tracking_frame tools/tracking_frame_cli.cpp)
sam3_add_native_tool(sam3_tracking_session tools/tracking_session_cli.cpp)
sam3_add_native_tool(sam3_tracking_video tools/tracking_video_cli.cpp)
add_executable(sam3_multiplex_video tools/tracking_video_cli.cpp)
target_compile_definitions(sam3_multiplex_video PRIVATE SAM3_MULTIPLEX_VIDEO=1)
target_link_libraries(sam3_multiplex_video PRIVATE sam3_native)
sam3_add_native_tool(sam3_multiplex_frame tools/multiplex_frame_cli.cpp)
sam3_add_native_tool(sam3_multiplex_update tools/multiplex_update_cli.cpp)
sam3_add_native_tool(sam3_multiplex_history tools/multiplex_history_cli.cpp)
sam3_add_native_tool(sam3_multiplex_session tools/multiplex_session_cli.cpp)
sam3_add_native_tool(sam3_detector_transformer tools/detector_cli.cpp)
sam3_add_native_tool(sam3_geometry tools/geometry_cli.cpp)
sam3_add_native_tool(sam3_vision_positions_benchmark tools/vision_positions_benchmark.cpp)
if(SAM3_WITH_CUDA)
  target_compile_definitions(sam3_vision_positions_benchmark PRIVATE SAM3_BENCH_CUDA)
endif()
sam3_add_native_tool(sam3_vision tools/vision_cli.cpp)
sam3_add_native_tool(sam3_video_predictor_probe tools/video_predictor_cli.cpp)
sam3_add_native_tool(sam3_image_predictor_probe tools/image_predictor_cli.cpp)
sam3_add_native_tool(sam3_video_pipeline_probe tools/video_pipeline_cli.cpp)
sam3_add_native_tool(sam3_video_interaction_test tests/video_interaction_test.cpp)
sam3_add_native_tool(sam3_video_output_test tests/video_output_test.cpp)
sam3_add_native_tool(sam3_video_multidevice_probe tools/video_multidevice_probe.cpp)
sam3_add_native_tool(sam3_video_collective_probe tools/video_collective_probe.cpp)
add_executable(sam3_rank_executor_test tests/rank_executor_test.cpp)
target_link_libraries(sam3_rank_executor_test PRIVATE sam3_native Threads::Threads)
sam3_add_native_tool(sam3_video_collective_test tests/video_collective_test.cpp)
sam3_add_native_tool(sam3_video_update_test tests/video_update_test.cpp)
sam3_add_native_tool(sam3_video_objects_test tests/video_objects_test.cpp)
sam3_add_native_tool(sam3_video_memory_test tests/video_memory_test.cpp)
sam3_add_native_tool(sam3_occlusion_test tests/occlusion_test.cpp)
sam3_add_native_tool(sam3_hotstart_test tests/hotstart_test.cpp)
sam3_add_native_tool(sam3_association_test tests/association_test.cpp)
sam3_add_native_tool(sam3_c_api_probe tools/c_api_probe.c)
if(NOT MSVC)
  target_link_libraries(sam3_c_api_probe PRIVATE m)
endif()
set_target_properties(sam3_c_api_probe PROPERTIES LINKER_LANGUAGE CXX C_STANDARD 11)
sam3_add_native_tool(sam3_predictor_c_probe tools/predictor_c_probe.c)
set_target_properties(sam3_predictor_c_probe PROPERTIES LINKER_LANGUAGE CXX C_STANDARD 11)
sam3_add_native_tool(sam3_c_api_thread_test tests/c_api_threads.cpp)
sam3_add_native_tool(sam3_c_api_test tests/c_api_smoke.c)
set_target_properties(sam3_c_api_test PROPERTIES LINKER_LANGUAGE CXX C_STANDARD 11)
sam3_add_native_tool(sam3_tensor_archive_test tests/tensor_archive_test.cpp)
if(MSVC)
  file(GLOB TORCH_DLLS "${TORCH_INSTALL_PREFIX}/lib/*.dll")
  if(SAM3_WITH_CUDA)
    add_custom_command(TARGET sam3_compute_storage_probe POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E copy_if_different ${TORCH_DLLS} $<TARGET_FILE_DIR:sam3_compute_storage_probe>)
    foreach(target sam3_vision_position_stream_test sam3_vision_fusion_benchmark sam3_vision_fusion_stream_test sam3_rotary_pair_stream_test)
      add_custom_command(TARGET ${target} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different ${TORCH_DLLS} $<TARGET_FILE_DIR:${target}>)
    endforeach()
    add_custom_command(TARGET sam3_rotary_stream_test POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E copy_if_different ${TORCH_DLLS} $<TARGET_FILE_DIR:sam3_rotary_stream_test>)
  endif()
  foreach(target sam3_vision_experiments_test sam3_vision_position_test sam3_rotary_pair_test sam3_vision_fusion_test sam3_inference_settings_test sam3_semantic_text_probe sam3_weights_large_test sam3_video_cache_fetch_probe sam3_video_mask_cache_benchmark sam3_video_mask_cache_test sam3_rotary_test sam3_native sam3_native_smoke sam3_native_ops_test sam3_native_weights_test sam3_native_multiplex_test sam3_weights sam3_text sam3_tokenize sam3_tokenizer_test sam3_vision sam3_vision_positions_benchmark sam3_geometry sam3_detector_transformer sam3_image_probe sam3_image_benchmark sam3_image_results_test sam3_interactive sam3_interactive_image sam3_video_heads sam3_memory sam3_memory_attention sam3_temporal sam3_multiplex_propagation sam3_tracking_frame sam3_tracking_session sam3_multiplex_temporal sam3_tracking_video sam3_multiplex_frame sam3_multiplex_update sam3_multiplex_history sam3_multiplex_session sam3_multiplex_video sam3_tensor_archive_test sam3_c_api_test sam3_c_api_probe sam3_predictor_c_probe sam3_c_api_thread_test sam3_association_test sam3_hotstart_test sam3_occlusion_test sam3_video_memory_test sam3_video_objects_test sam3_video_update_test sam3_rank_executor_test sam3_video_collective_test sam3_video_collective_probe sam3_video_multidevice_probe sam3_video_pipeline_probe sam3_video_predictor_probe sam3_image_predictor_probe sam3_video_output_test sam3_video_interaction_test)
    add_custom_command(TARGET ${target} POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E copy_if_different ${TORCH_DLLS} $<TARGET_FILE_DIR:${target}>)
  endforeach()
endif()
enable_testing()
add_test(NAME rotary_cpu COMMAND sam3_rotary_test cpu)
add_test(NAME weights_crc_large_cpu COMMAND sam3_weights_large_test)
add_test(NAME inference_settings_cpu COMMAND sam3_inference_settings_test)
add_test(NAME video_mask_cache_cpu COMMAND sam3_video_mask_cache_test cpu)
add_test(NAME image_results_cpu COMMAND sam3_image_results_test cpu)
add_test(NAME video_interaction_cpu COMMAND sam3_video_interaction_test)
add_test(NAME video_output_cpu COMMAND sam3_video_output_test cpu)
add_test(NAME rank_executor_cpu COMMAND sam3_rank_executor_test cpu)
add_test(NAME video_collective_cpu COMMAND sam3_video_collective_test cpu)
add_test(NAME video_update_cpu COMMAND sam3_video_update_test cpu)
add_test(NAME video_objects_cpu COMMAND sam3_video_objects_test cpu)
add_test(NAME video_memory_cpu COMMAND sam3_video_memory_test cpu)
add_test(NAME occlusion_cpu COMMAND sam3_occlusion_test cpu)
add_test(NAME hotstart_cpu COMMAND sam3_hotstart_test cpu)
add_test(NAME association_cpu COMMAND sam3_association_test cpu)
add_test(NAME c_api COMMAND sam3_c_api_test)
add_test(NAME c_api_threads COMMAND sam3_c_api_thread_test)
add_test(NAME archive_cpu COMMAND sam3_tensor_archive_test cpu)
add_test(NAME native_cpu COMMAND sam3_native_smoke cpu)
add_test(NAME ops_cpu COMMAND sam3_native_ops_test cpu)
add_test(NAME weights_cpu COMMAND sam3_native_weights_test cpu)
add_test(NAME multiplex_cpu COMMAND sam3_native_multiplex_test cpu)
add_test(NAME tokenizer_cpu COMMAND sam3_tokenizer_test "${CMAKE_CURRENT_SOURCE_DIR}/../sam3/assets/bpe_simple_vocab_16e6.txt.gz")
if(SAM3_TEST_CUDA)
  if(NOT SAM3_WITH_CUDA)
    message(FATAL_ERROR "SAM3_TEST_CUDA requires SAM3_WITH_CUDA")
  endif()
  add_test(NAME image_results_cuda COMMAND sam3_image_results_test cuda)
  add_test(NAME video_output_cuda COMMAND sam3_video_output_test cuda)
  add_test(NAME rank_executor_cuda COMMAND sam3_rank_executor_test cuda)
  add_test(NAME video_collective_cuda COMMAND sam3_video_collective_test cuda)
  add_test(NAME video_update_cuda COMMAND sam3_video_update_test cuda)
  add_test(NAME video_objects_cuda COMMAND sam3_video_objects_test cuda)
  add_test(NAME video_memory_cuda COMMAND sam3_video_memory_test cuda)
  add_test(NAME occlusion_cuda COMMAND sam3_occlusion_test cuda)
  add_test(NAME hotstart_cuda COMMAND sam3_hotstart_test cuda)
  add_test(NAME association_cuda COMMAND sam3_association_test cuda fp16)
  add_test(NAME archive_cuda COMMAND sam3_tensor_archive_test cuda)
  add_test(NAME native_cuda COMMAND sam3_native_smoke cuda)
  add_test(NAME ops_cuda COMMAND sam3_native_ops_test cuda)
  add_test(NAME vision_position_cuda COMMAND sam3_vision_position_test cuda)
  add_test(NAME vision_position_stream_cuda COMMAND sam3_vision_position_stream_test cuda)
  add_test(NAME rotary_pair_cuda COMMAND sam3_rotary_pair_test cuda)
  add_test(NAME rotary_pair_stream_cuda COMMAND sam3_rotary_pair_stream_test cuda)
  add_test(NAME vision_fusion_stream_cuda COMMAND sam3_vision_fusion_stream_test)
  add_test(NAME vision_fusion_cuda COMMAND sam3_vision_fusion_test cuda)
  add_test(NAME rotary_cuda COMMAND sam3_rotary_test cuda)
  add_test(NAME video_mask_cache_cuda COMMAND sam3_video_mask_cache_test cuda)
  add_test(NAME rotary_stream_cuda COMMAND sam3_rotary_stream_test cuda)
  add_test(NAME weights_cuda COMMAND sam3_native_weights_test cuda)
  add_test(NAME multiplex_cuda COMMAND sam3_native_multiplex_test cuda fp16)
endif()
