option(SAM3_WITH_MEDIA "Enable native local-file image/video decoding and PNG output" OFF)
target_sources(sam3_native PRIVATE src/media.cpp src/c_api_media.cpp)
if(SAM3_WITH_MEDIA)
  set(SAM3_FFMPEG_ROOT "" CACHE PATH "FFmpeg shared development distribution root")
  find_path(SAM3_AV_INCLUDE libavformat/avformat.h HINTS "${SAM3_FFMPEG_ROOT}/include" REQUIRED)
  foreach(component avformat avcodec avutil swscale)
    find_library(SAM3_${component}_LIBRARY NAMES ${component} HINTS "${SAM3_FFMPEG_ROOT}/lib" REQUIRED)
    target_link_libraries(sam3_native PRIVATE "${SAM3_${component}_LIBRARY}")
  endforeach()
  find_package(JPEG REQUIRED)
  set_property(SOURCE src/media.cpp APPEND PROPERTY INCLUDE_DIRECTORIES "${SAM3_AV_INCLUDE}")
  target_link_libraries(sam3_native PRIVATE JPEG::JPEG)
  set_property(SOURCE src/media.cpp APPEND PROPERTY COMPILE_DEFINITIONS SAM3_WITH_MEDIA)
endif()
