# Source inventory for the native runtime. Paths are relative to native/.
set(sam3_vision_sources src/vision_encoder.cpp src/vision_attention.cpp src/vision_block.cpp)
add_library(sam3_native SHARED
  src/interactive_image.cpp
  src/interactive_decoder.cpp
  src/interactive_prompt.cpp
  src/tokenizer.cpp
  src/roi_align.cpp
  src/ops.cpp
  src/edt.cpp
  src/components.cpp
  src/weights.cpp
  src/image_results.cpp
  src/grounding.cpp
  src/detection_heads.cpp
  src/detector_decoder.cpp
  src/detector_encoder.cpp
  src/geometry_encoder.cpp
  src/text_encoder.cpp
  ${sam3_vision_sources}
  src/preprocess.cpp
  src/register.cpp
  src/c_api.cpp
  src/c_api_image.cpp
  src/c_api_video.cpp
  src/c_api_predictor.cpp
  src/association.cpp
  src/association_register.cpp
  src/hotstart.cpp
  src/hotstart_register.cpp
  src/occlusion.cpp
  src/occlusion_register.cpp
  src/video_recondition.cpp
  src/video_memory.cpp
  src/video_memory_register.cpp
  src/video_objects.cpp
  src/video_objects_register.cpp
  src/video_collective.cpp
  src/video_update.cpp
  src/video_update_register.cpp
  src/video_frame.cpp
  src/video_frame_register.cpp
  src/video_output.cpp
  src/video_output_register.cpp
  src/video_interaction.cpp
  src/video_interaction_register.cpp
  src/video_edit.cpp
  src/video_predictor.cpp
  src/video_heads.cpp
  src/memory_encoder.cpp
  src/memory_attention.cpp
  src/rotary.cpp
  src/vision_fusion.cpp
  src/rotary_pair.cpp
  src/vision_position.cpp
  src/video_mask_cache.cpp
  src/temporal_memory.cpp
  src/multiplex.cpp
  src/multiplex_decoder.cpp
  src/multiplex_temporal.cpp
  src/tracking_frame.cpp
  src/tracking_session.cpp
  src/tracking_session_register.cpp
  src/profile_range.cpp
  src/tracking_preprocess.cpp
  src/tracking_vision.cpp
  src/multiplex_frame.cpp
  src/multiplex_frame_register.cpp
  src/multiplex_update_register.cpp
  src/multiplex_history.cpp
  src/multiplex_history_register.cpp
  src/multiplex_session.cpp
  src/tensor_archive.cpp
  src/multiplex_storage.cpp
  src/multiplex_vision.cpp
  src/multiplex_session_register.cpp
)
