#include "media_internal.h"
using namespace sam3::api;
namespace {void available(){if(!sam3::media_available())throw Failure(SAM3_UNSUPPORTED,"build with SAM3_WITH_MEDIA=ON to enable native media");}}
extern "C" {
int32_t sam3_media_available(void) noexcept{return sam3::media_available();}
sam3_status sam3_media_options_init(sam3_media_options* o) noexcept{return protect([&]{require(o,"media options are required");*o={};o->struct_size=sizeof(*o);o->threads=1;});}
sam3_status sam3_media_open(const char* path,const sam3_media_options* o,sam3_media** out) noexcept{return sam3_media_open_with_color(path,o,SAM3_MEDIA_COLOR_STREAM,out);}
sam3_status sam3_media_open_with_color(const char* path,const sam3_media_options* o,int32_t color,sam3_media** out) noexcept{return protect([&]{output(out);available();options(o);require(color==SAM3_MEDIA_COLOR_STREAM || color==SAM3_MEDIA_COLOR_OPENCV,"invalid color policy");require(path && *path && o->threads>0,"path and positive thread count are required");auto handle=std::make_unique<sam3_media>();handle->value=std::make_shared<sam3::MediaSource>(std::filesystem::u8path(path),sam3::MediaOptions{bool(o->image_only),o->threads},static_cast<sam3::MediaColorPolicy>(color));*out=handle.release();});}
void sam3_media_release(sam3_media* p) noexcept{delete p;}
sam3_status sam3_media_info(sam3_media* p,sam3_result** out) noexcept{return protect([&]{output(out);require(p,"media is required");const auto& i=p->value->info();result({{"frames",at::scalar_tensor(i.frames,at::kLong)},{"height",at::scalar_tensor(i.height,at::kLong)},{"width",at::scalar_tensor(i.width,at::kLong)},{"fps",at::scalar_tensor(i.fps,at::kDouble)},{"image_only",at::scalar_tensor(i.image_only,at::kBool)}},out);});}
sam3_status sam3_media_stats(sam3_media* p,sam3_result** out) noexcept{return protect([&]{output(out);require(p,"media is required");const auto i=p->value->stats();result({{"index_decoded_frames",at::scalar_tensor(i.index_decoded_frames,at::kLong)},{"read_decoded_frames",at::scalar_tensor(i.read_decoded_frames,at::kLong)},{"seek_attempts",at::scalar_tensor(i.seek_attempts,at::kLong)},{"seek_fallbacks",at::scalar_tensor(i.seek_fallbacks,at::kLong)},{"cache_hits",at::scalar_tensor(i.cache_hits,at::kLong)},{"cache_bytes",at::scalar_tensor(i.cache_bytes,at::kLong)},{"cache_limit_bytes",at::scalar_tensor(i.cache_limit_bytes,at::kLong)},{"indexed_seek_enabled",at::scalar_tensor(i.indexed_seek_enabled,at::kBool)}},out);});}
sam3_status sam3_media_set_cache_bytes(sam3_media* p,int64_t bytes) noexcept{return protect([&]{require(p && bytes>=0,"media and nonnegative cache bytes are required");p->value->set_cache_bytes(bytes);});}
sam3_status sam3_media_read_frame(sam3_media* p,int64_t frame,sam3_result** out) noexcept{return protect([&]{output(out);require(p && frame>=0 && frame<p->value->info().frames,"media and in-range frame index are required");const auto f=p->value->read(frame);result({{"rgb",f.rgb},{"seconds",at::scalar_tensor(f.seconds,at::kDouble)},{"duration",at::scalar_tensor(f.duration,at::kDouble)}},out);});}
sam3_status sam3_media_write_png(const char* path,const sam3_rgb_view* view) noexcept{return protect([&]{available();require(path && *path && view,"output path and RGB view are required");sam3::write_rgb_png(std::filesystem::u8path(path),rgb(*view));});}
}
