#include "sam3/hotstart.h"
#include <torch/library.h>
namespace {
using Dict=c10::Dict<std::string,at::Tensor>;
sam3::HotstartOptions options(const std::vector<int64_t>& x){TORCH_CHECK(x.size()==8,"expected eight hotstart options");return {x[0],x[1],x[2],x[3],x[4],x[5],bool(x[6]),bool(x[7])};}
std::vector<int64_t> integers(const at::Tensor& input){TORCH_CHECK(input.device().is_cpu() && input.scalar_type()==at::kLong,"host metadata must be CPU int64");const auto x=input.contiguous().view({-1});if(!x.numel())return {};return {x.const_data_ptr<int64_t>(),x.const_data_ptr<int64_t>()+x.numel()};}
std::map<int64_t,std::vector<int64_t>> matches(const std::vector<int64_t>& keys,const std::vector<std::vector<int64_t>>& values){TORCH_CHECK(keys.size()==values.size(),"match keys/value size mismatch");std::map<int64_t,std::vector<int64_t>> out;for(size_t i=0;i<keys.size();++i)out[keys[i]]=values[i];return out;}
void put(Dict& out,const std::string& name,const std::vector<int64_t>& values){out.insert(name,at::tensor(values,at::kLong));}
sam3::DeviceHotstartState device_state(const Dict& x,at::Device device){if(!x.contains("obj_first_frame"))return sam3::empty_device_hotstart(device);auto s=sam3::DeviceHotstartState{x.at("obj_first_frame"),x.at("consecutive_unmatch_count"),x.at("trk_keep_alive"),x.at("removed_mask"),x.at("overlap_pair_counts"),x.at("last_occluded_tensor")};if(x.contains("N_obj"))TORCH_CHECK(x.at("N_obj").item<int64_t>()==s.size(),"N_obj mismatch");return s;}
Dict device_dict(const sam3::DeviceHotstartState& s){Dict out;out.insert("N_obj",at::scalar_tensor(s.size(),at::kLong));out.insert("obj_first_frame",s.first_frame);out.insert("consecutive_unmatch_count",s.unmatched_count);out.insert("trk_keep_alive",s.keep_alive);out.insert("removed_mask",s.removed);out.insert("overlap_pair_counts",s.overlap_count);out.insert("last_occluded_tensor",s.last_occluded);return out;}
sam3::HostHotstartState host_state(const Dict& x){
  sam3::HostHotstartState s;if(x.empty())return s;
  const auto mapping=[&](const char* name,auto& out){const auto v=integers(x.at(name));TORCH_CHECK(v.size()%2==0,"invalid key/value pairs");for(size_t i=0;i<v.size();i+=2)out[v[i]]=v[i+1];};mapping("first_frame",s.first_frame);mapping("keep_alive",s.keep_alive);
  const auto lists=[&](const std::string& name,int64_t width,auto emit){const auto keys=integers(x.at(name+"_keys")),offsets=integers(x.at(name+"_offsets")),values=integers(x.at(name+"_values"));TORCH_CHECK(keys.size()%width==0 && offsets.size()==keys.size()/width+1 && offsets.front()==0 && offsets.back()==int64_t(values.size()),"invalid ragged state");for(size_t i=0;i+1<offsets.size();++i){TORCH_CHECK(offsets[i]>=0 && offsets[i]<=offsets[i+1] && offsets[i+1]<=int64_t(values.size()),"invalid state offset");emit(keys,i*width,std::vector<int64_t>(values.begin()+offsets[i],values.begin()+offsets[i+1]));}};
  lists("unmatched",1,[&](const auto& k,size_t i,const auto& v){s.unmatched_frames[k[i]]=v;});lists("overlap",2,[&](const auto& k,size_t i,const auto& v){s.overlap_frames[{k[i],k[i+1]}]=v;});lists("suppressed",1,[&](const auto& k,size_t i,const auto& v){s.suppressed[k[i]]={v.begin(),v.end()};});const auto removed=integers(x.at("removed"));s.removed={removed.begin(),removed.end()};return s;
}
Dict host_dict(const sam3::HostHotstartState& s){
  Dict out;const auto mapping=[&](const char* name,const auto& value){std::vector<int64_t> data;for(const auto& [k,v]:value){data.push_back(k);data.push_back(v);}out.insert(name,at::tensor(data,at::kLong).reshape({-1,2}));};mapping("first_frame",s.first_frame);mapping("keep_alive",s.keep_alive);
  std::vector<int64_t> keys,offsets,values;const auto reset=[&]{keys.clear();offsets={0};values.clear();};const auto emit=[&](const std::string& name,int64_t width){out.insert(name+"_keys",at::tensor(keys,at::kLong).reshape({-1,width}));put(out,name+"_offsets",offsets);put(out,name+"_values",values);};
  reset();for(const auto& [k,v]:s.unmatched_frames){keys.push_back(k);values.insert(values.end(),v.begin(),v.end());offsets.push_back(values.size());}emit("unmatched",1);
  reset();for(const auto& [k,v]:s.overlap_frames){keys.push_back(k.first);keys.push_back(k.second);values.insert(values.end(),v.begin(),v.end());offsets.push_back(values.size());}emit("overlap",2);
  reset();for(const auto& [k,v]:s.suppressed){keys.push_back(k);values.insert(values.end(),v.begin(),v.end());offsets.push_back(values.size());}emit("suppressed",1);put(out,"removed",{s.removed.begin(),s.removed.end()});return out;
}
}
TORCH_LIBRARY_FRAGMENT(sam3_native,m){
  m.def("hotstart_host(Dict(str,Tensor) state, int[] det_keys, int[][] det_tracks, int[] unmatched, int[] empty, int[] new_ids, int frame, bool reverse, int[] options) -> Dict(str,Tensor)",[](const Dict& state,const std::vector<int64_t>& keys,const std::vector<std::vector<int64_t>>& values,const std::vector<int64_t>& unmatched,const std::vector<int64_t>& empty,const std::vector<int64_t>& new_ids,int64_t frame,bool reverse,const std::vector<int64_t>& config){sam3::AssociationMetadata a;a.detection_to_tracks=matches(keys,values);a.unmatched_tracks=unmatched;a.empty_tracks=empty;const auto result=sam3::update_host_hotstart(host_state(state),a,new_ids,frame,reverse,options(config));auto out=host_dict(result.state);put(out,"newly_removed",{result.newly_removed.begin(),result.newly_removed.end()});return out;});
  m.def("hotstart_device(Dict(str,Tensor) state, Tensor unmatched, Tensor nonempty, Tensor matches, int frame, bool reverse, int[] options) -> Dict(str,Tensor)",[](const Dict& state,const at::Tensor& unmatched,const at::Tensor& nonempty,const at::Tensor& match,int64_t frame,bool reverse,const std::vector<int64_t>& config){sam3::AssociationTensors a;a.unmatched=unmatched;a.nonempty=nonempty;a.matches=match;const auto result=sam3::update_device_hotstart(device_state(state,match.device()),a,frame,reverse,options(config));auto out=device_dict(result.state);out.insert("remove",result.remove);out.insert("suppress",result.suppress);return out;});
  m.def("hotstart_extend(Dict(str,Tensor) state, int count, int frame, int initial, str device) -> Dict(str,Tensor)",[](const Dict& state,int64_t count,int64_t frame,int64_t initial,const std::string& device){return device_dict(sam3::extend_device_hotstart(device_state(state,at::Device(device)),count,frame,initial));});
  m.def("hotstart_compact(Dict(str,Tensor) state) -> Dict(str,Tensor)",[](const Dict& state){const auto result=sam3::compact_device_hotstart(device_state(state,at::kCPU));auto out=device_dict(result.first);out.insert("indices",result.second);return out;});
  m.def("hotstart_select(Dict(str,Tensor) state, Tensor indices) -> Dict(str,Tensor)",[](const Dict& state,const at::Tensor& indices){return device_dict(sam3::select_device_hotstart(device_state(state,indices.device()),indices));});
  m.def("confirmation(int[] status, int[] count, int[] previous_ids, int[] updated_ids, int[] det_keys, int[][] det_tracks, int[] new_ids, int threshold) -> (Tensor,Tensor)",[](const std::vector<int64_t>& status,const std::vector<int64_t>& count,const std::vector<int64_t>& previous,const std::vector<int64_t>& updated,const std::vector<int64_t>& keys,const std::vector<std::vector<int64_t>>& tracks,const std::vector<int64_t>& new_ids,int64_t threshold){const auto out=sam3::update_confirmation({status,count},previous,updated,matches(keys,tracks),new_ids,threshold);return std::make_tuple(at::tensor(out.status,at::kLong),at::tensor(out.consecutive_detections,at::kLong));});
}
