#include "sam3/occlusion.h"
#include "sam3/autocast.h"
#include <torch/library.h>
namespace {
using Dict=c10::Dict<std::string,at::Tensor>;
sam3::ReconditionCandidates candidates(const std::vector<int64_t>& ids,const std::vector<int64_t>& det){TORCH_CHECK(ids.size()==det.size(),"candidate size mismatch");sam3::ReconditionCandidates out;for(size_t i=0;i<ids.size();++i)out.emplace_back(ids[i],det[i]);return out;}
sam3::AssociationPolicy policy(bool multiplex){return multiplex?sam3::AssociationPolicy::Sam31:sam3::AssociationPolicy::Sam3;}
}
TORCH_LIBRARY_FRAGMENT(sam3_native,m){
  m.def("occlusion(Tensor masks, Tensor last, Tensor removed, Tensor? known, int frame, bool reverse, bool multiplex, float threshold, bool allow, str mode) -> Tensor[]",[](const at::Tensor& masks,const at::Tensor& last,const at::Tensor& removed,const std::optional<at::Tensor>& known,int64_t frame,bool reverse,bool mux,double threshold,bool allow,const std::string& mode){const auto out=sam3::update_occlusion(masks,last,removed,frame,reverse,{policy(mux),threshold,allow},known.value_or(at::Tensor()),mode);return std::vector<at::Tensor>{out.masks,out.suppressed,out.last_occluded};});
  m.def("occlusion_host(Dict(int,Tensor) history, int[] ids, Tensor masks, int[] removed, int frame, bool reverse, float threshold, str mode) -> Dict(str,Tensor)",[](const c10::Dict<int64_t,at::Tensor>& history,const std::vector<int64_t>& ids,const at::Tensor& masks,const std::vector<int64_t>& removed,int64_t frame,bool reverse,double threshold,const std::string& mode){std::map<int64_t,at::Tensor> state;for(const auto& item:history)state.emplace(item.key(),item.value());const auto value=sam3::update_host_occlusion(state,ids,masks,{removed.begin(),removed.end()},frame,reverse,threshold,mode);Dict out;out.insert("masks",value.masks);out.insert("suppressed",value.suppressed);std::vector<int64_t> keys;std::vector<at::Tensor> values;for(const auto& [id,t]:value.history){keys.push_back(id);values.push_back(t);}out.insert("history_ids",at::tensor(keys,at::kLong));out.insert("history_values",values.empty()?at::empty({0},masks.options().dtype(at::kLong)):at::cat(values));return out;});
  m.def("occlusion_hotstart(Dict(str,Tensor) state, Tensor masks, Tensor removed, int frame, bool reverse, float threshold, bool allow, str mode) -> Dict(str,Tensor)",[](const Dict& state,const at::Tensor& masks,const at::Tensor& removed,int64_t frame,bool reverse,double threshold,bool allow,const std::string& mode){sam3::DeviceHotstartState s{state.at("obj_first_frame"),state.at("consecutive_unmatch_count"),state.at("trk_keep_alive"),state.at("removed_mask"),state.at("overlap_pair_counts"),state.at("last_occluded_tensor")};const auto result=sam3::update_device_occlusion(s,masks,removed,frame,reverse,threshold,allow,mode);Dict out;for(const auto& value:state)out.insert(value.key(),value.value());out.insert_or_assign("last_occluded_tensor",result.state.last_occluded);out.insert_or_assign("masks",result.masks);out.insert_or_assign("suppressed",result.suppressed);return out;});
  m.def("tracking_mask_boxes(Tensor masks) -> Tensor",&sam3::tracking_mask_boxes);
  m.def("diagonal_box_iou(Tensor a, Tensor b, str mode) -> Tensor",[](const at::Tensor& a,const at::Tensor& b,const std::string& mode){sam3::AutocastGuard guard(a.device().type(),mode!="fp32",mode=="fp16"?at::kHalf:at::kBFloat16);return sam3::diagonal_box_iou(a,b);});
  m.def("clean_video_masks(Tensor masks, int area, bool holes, bool sprinkles) -> Tensor",&sam3::clean_video_mask_scores);
  m.def("recondition_gate(int[] candidate_ids, int[] candidate_dets, int[] ids, Tensor boxes, Tensor scores, Tensor masks, int frame, bool multiplex, int period, float iou, float score, str mode) -> (bool,bool,int[])",[](const std::vector<int64_t>& ci,const std::vector<int64_t>& cd,const std::vector<int64_t>& ids,const at::Tensor& boxes,const at::Tensor& scores,const at::Tensor& masks,int64_t frame,bool mux,int64_t period,double iou,double score,const std::string& mode){const auto out=sam3::recondition_decision(candidates(ci,cd),ids,boxes,scores,masks,frame,{policy(mux),period,iou,score},mode);return std::make_tuple(out.periodic,out.geometry,std::vector<int64_t>(out.geometry_ids.begin(),out.geometry_ids.end()));});
  m.def("recondition_prepare(int[] candidate_ids, int[] candidate_dets, int[] ids, Tensor detections, Tensor scores, Tensor masks, int height, int width, bool multiplex, int area, int[][] state_ids, bool grouped, str mode) -> Dict(str,Tensor)",[](const std::vector<int64_t>& ci,const std::vector<int64_t>& cd,const std::vector<int64_t>& ids,const at::Tensor& det,const at::Tensor& scores,const at::Tensor& masks,int64_t h,int64_t w,bool mux,int64_t area,const std::vector<std::vector<int64_t>>& states,bool grouped,const std::string& mode){const auto out=sam3::prepare_recondition_masks(candidates(ci,cd),ids,det,scores,masks,h,w,policy(mux),area,mode);const auto batches=sam3::recondition_batches(out,states,policy(mux),grouped);Dict result;result.insert("ids",at::tensor(out.ids,at::kLong));result.insert("detection_indices",at::tensor(out.detection_indices,at::kLong));result.insert("track_indices",at::tensor(out.track_indices,at::kLong));result.insert("binary_masks",out.binary_masks);result.insert("low_masks",out.low_masks);std::vector<int64_t> batch_states,batch_offsets{0},batch_ids;std::vector<at::Tensor> batch_masks;for(const auto& batch:batches){batch_states.push_back(batch.state_index);batch_ids.insert(batch_ids.end(),batch.ids.begin(),batch.ids.end());batch_offsets.push_back(batch_ids.size());batch_masks.push_back(batch.masks);}result.insert("batch_states",at::tensor(batch_states,at::kLong));result.insert("batch_offsets",at::tensor(batch_offsets,at::kLong));result.insert("batch_ids",at::tensor(batch_ids,at::kLong));result.insert("batch_masks",batch_masks.empty()?at::empty({0,h,w},masks.options().dtype(at::kBool)):at::cat(batch_masks));return result;});
}
