#include "sam3/video_interaction.h"
#include <torch/library.h>
namespace {using Dict=c10::Dict<std::string,at::Tensor>;}
TORCH_LIBRARY_FRAGMENT(sam3_native,m){
 m.def("video_action_route(int[] types, int[] frames, int[][] ids, bool[] has_ids, int count, bool multiplex, int[] initialized, int start=-1, int steps=-1, bool reverse=False) -> Dict(str, Tensor)",[](const std::vector<int64_t>& types,const std::vector<int64_t>& frames,const std::vector<std::vector<int64_t>>& ids,const c10::List<bool>& has,int64_t count,bool mux,const std::vector<int64_t>& initialized,int64_t start,int64_t steps,bool reverse){
  TORCH_CHECK(types.size()==frames.size() && types.size()==ids.size() && types.size()==has.size(),"invalid action fixture");sam3::VideoInteractionState state(mux?sam3::AssociationPolicy::Sam31:sam3::AssociationPolicy::Sam3,count,3,5);
  for(size_t i=0;i<types.size();++i)state.append({sam3::VideoActionType(types[i]),frames[i]<0?std::nullopt:std::make_optional(frames[i]),has[i]?std::make_optional(ids[i]):std::nullopt});const auto route=state.route();Dict out;out.insert("type",at::scalar_tensor(int64_t(route.type),at::kLong));out.insert("has_ids",at::scalar_tensor(bool(route.ids),at::kBool));out.insert("ids",at::tensor(route.ids.value_or(std::vector<int64_t>{}),at::kLong));
  const auto range=sam3::video_processing_range(count,{initialized.begin(),initialized.end()},start<0?std::nullopt:std::make_optional(start),steps<0?std::nullopt:std::make_optional(steps),reverse);out.insert("range",at::tensor({range.first,range.end,range.step,int64_t(range.empty)},at::kLong));return out;
 });
 m.def("video_refinement_merge(Tensor masks, int[] ids, Tensor scores, Tensor tracker_scores, Tensor refined, int[] refined_ids, Tensor refined_scores, int[] suppressed, bool multiplex, bool cached=True) -> Dict(str, Tensor)",[](const at::Tensor& masks,const std::vector<int64_t>& ids,const at::Tensor& scores,const at::Tensor& trackers,const at::Tensor& refined,const std::vector<int64_t>& refined_ids,const at::Tensor& refined_scores,const std::vector<int64_t>& suppressed,bool mux,bool cached){
  TORCH_CHECK(masks.dim()==3 && masks.size(0)==int64_t(ids.size()) && scores.numel()==int64_t(ids.size()) && trackers.numel()==int64_t(ids.size()) && refined.dim()==3 && refined.size(0)==int64_t(refined_ids.size()) && refined_scores.numel()==int64_t(refined_ids.size()),"invalid merge fixture");sam3::VideoInteractionState state(mux?sam3::AssociationPolicy::Sam31:sam3::AssociationPolicy::Sam3,3,masks.size(1),masks.size(2));sam3::VideoMetadata metadata;sam3::VideoOutput cache;
  for(size_t i=0;i<ids.size();++i){cache.cached_masks.emplace(ids[i],masks.slice(0,i,i+1));metadata.object_scores[ids[i]]=scores[i].item<double>();metadata.frame_scores[1][ids[i]]=trackers[i];}if(cached)state.record(1,cache);sam3::RefinedVideoObjects updates;
  for(size_t i=0;i<refined_ids.size();++i){metadata.object_scores[refined_ids[i]]=1.;updates[refined_ids[i]]={refined_scores[i],refined[i]};}
  const auto result=state.merge_refined(1,updates,metadata,{suppressed.begin(),suppressed.end()});Dict out;out.insert("ids",result.ids);out.insert("scores",result.probabilities);out.insert("boxes",result.boxes_xywh.cpu());out.insert("masks",result.masks.cpu());for(const auto& [id,x]:result.cached_masks)out.insert("cache/"+std::to_string(id),x.cpu());for(const auto& [id,x]:metadata.frame_scores[1])out.insert("tracker/"+std::to_string(id),x.cpu());return out;
 });
}
